"use strict";var __read=this&&this.__read||function(o,n){var e="function"==typeof Symbol&&o[Symbol.iterator];if(!e)return o;var a,t,i=e.call(o),m=[];try{for(;(void 0===n||n-- >0)&&!(a=i.next()).done;)m.push(a.value)}catch(o){t={error:o}}finally{try{a&&!a.done&&(e=i.return)&&e.call(i)}finally{if(t)throw t.error}}return m},__spread=this&&this.__spread||function(){for(var o=[],n=0;n<arguments.length;n++)o=o.concat(__read(arguments[n]));return o};Object.defineProperty(exports,"__esModule",{value:!0});var command_1=require("./command"),CommandMap_1=require("./command/CommandMap"),CmpApiModel_1=require("./CmpApiModel"),Disabled_1=require("./response/Disabled"),SupportedVersions_1=require("./SupportedVersions");exports.API_KEY="__tcfapi";var CallResponder=function(){function o(o){var n,e;if(o){var a=command_1.TCFCommand.ADD_EVENT_LISTENER;if(null===(n=o)||void 0===n?void 0:n[a])throw new Error("Built-In Custom Commmand for "+a+" not allowed: Use "+command_1.TCFCommand.GET_TC_DATA+" instead");if(a=command_1.TCFCommand.REMOVE_EVENT_LISTENER,null===(e=o)||void 0===e?void 0:e[a])throw new Error("Built-In Custom Commmand for "+a+" not allowed");this.customCommands=o}try{this.callQueue=window[exports.API_KEY]()||[]}catch(o){this.callQueue=[]}finally{
    //window[exports.API_KEY]=this.apiCall.bind(this),
    Object.defineProperty(window, exports.API_KEY,
        {
          value: this.apiCall.bind(this),
          writable: false,
          enumerable: false,
          configurable: false
        }
      );
    this.purgeQueuedCalls()}}return o.prototype.apiCall=function(o,n,e){for(var a,t=[],i=3;i<arguments.length;i++)t[i-3]=arguments[i];if("string"!=typeof o)e(null,!1);else if(SupportedVersions_1.SupportedVersions.has(n)){if("function"!=typeof e)throw new Error("invalid callback function");CmpApiModel_1.CmpApiModel.disabled?e(new Disabled_1.Disabled,!1):this.isCustomCommand(o)||this.isBuiltInCommand(o)?this.isCustomCommand(o)&&!this.isBuiltInCommand(o)?(a=this.customCommands)[o].apply(a,__spread([e],t)):o===command_1.TCFCommand.PING?this.isCustomCommand(o)?new CommandMap_1.CommandMap[o](this.customCommands[o],t[0],null,e):new CommandMap_1.CommandMap[o](e,t[0]):void 0===CmpApiModel_1.CmpApiModel.tcModel?this.callQueue.push(__spread([o,n,e],t)):this.isCustomCommand(o)&&this.isBuiltInCommand(o)?new CommandMap_1.CommandMap[o](this.customCommands[o],t[0],null,e):new CommandMap_1.CommandMap[o](e,t[0]):e(null,!1)}else e(null,!1)},o.prototype.purgeQueuedCalls=function(){var o=this.callQueue;this.callQueue=[],o.forEach((function(o){window[exports.API_KEY].apply(window,__spread(o))}))},o.prototype.isCustomCommand=function(o){return this.customCommands&&"function"==typeof this.customCommands[o]},o.prototype.isBuiltInCommand=function(o){return void 0!==CommandMap_1.CommandMap[o]},o}();exports.CallResponder=CallResponder;